apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubesql
  namespace: swelby
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-serv22
  template:
    metadata:
      labels:
        app: sql-serv22
    spec:
      containers:
      - name: sql-serv-sw
        image: ighost007/kubesql:latest
        ports:
        - containerPort: 3307
