apiVersion: v1
kind: Service
metadata:
  name: kubesql-service
  namespace: swelby
spec:
  type: NodePort
  ports:
  - port: 3307
    targetPort: 3307
    protocol: TCP
  selector:
    app: sql-serv22
